# Generated by Django 5.1.15 on 2026-06-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='office_name',
            field=models.CharField(blank=True, help_text='Administrative office name', max_length=120),
        ),
    ]
