# Generated by Django 5.1.15 on 2026-06-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0002_site_office_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['state__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
    ]
