# Generated by Django 5.1.15 on 2026-06-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
