# Generated by Django 5.1.15 on 2026-06-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payslip_bonus_payslip_tds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarystructure',
            options={'ordering': ['employee__emp_code']},
        ),
    ]
