# Generated by Django 5.1.15 on 2026-06-22 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_code', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('designation', models.CharField(max_length=80)),
                ('uan', models.CharField(blank=True, max_length=20)),
                ('esic_no', models.CharField(blank=True, max_length=20)),
                ('aadhar', models.CharField(blank=True, max_length=12)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('bank_account', models.CharField(blank=True, max_length=20)),
                ('ifsc', models.CharField(blank=True, max_length=11)),
                ('date_joined', models.DateField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='deployment.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('aadhar', 'Aadhar'), ('pan', 'PAN'), ('photo', 'Photo'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='employees/docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
