# Generated by Django 5.1.15 on 2026-06-22 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESIContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payslip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esi_contribution', to='payroll.payslip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PFContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payslip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pf_contribution', to='payroll.payslip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChallanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challan_type', models.CharField(choices=[('epf', 'EPF'), ('esi', 'ESI')], max_length=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_filed', models.BooleanField(default=False)),
                ('filed_on', models.DateField(blank=True, null=True)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='payroll.payrollrun')),
            ],
            options={
                'unique_together': {('payroll_run', 'challan_type')},
            },
        ),
    ]
